import { NextResponse } from "next/server";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    const { email, query, fullAnalysis } = await req.json();

    if (!email || !email.includes("@")) {
      return NextResponse.json({ error: "Valid email required" }, { status: 400 });
    }

    const userEmail = email.trim().toLowerCase();
    const userQuery = String(query || "Strategic Briefing");

    // Format the analysis into clean HTML sections
    const analysisHtml = Object.entries(fullAnalysis || {})
      .map(([agentKey, data]: [string, any]) => {
        return `
          <div style="margin-bottom: 30px; padding: 20px; background: #F9F9F9; border-left: 4px solid #FFD60A;">
            <h3 style="margin-top: 0; color: #1C1C1E; text-transform: uppercase; font-size: 14px; letter-spacing: 1px;">
              ${agentKey.replace('agent', 'Phase ')}
            </h3>
            <div style="color: #444; line-height: 1.6;">
              ${data?.summary || data?.recommendation || JSON.stringify(data)}
            </div>
          </div>
        `;
      }).join('');

    const { data, error } = await resend.emails.send({
      from: "My Briefing <onboarding@resend.dev>", // Update to your verified domain before launch
      to: [userEmail],
      subject: `My Briefing: ${userQuery}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #1C1C1E;">
          <header style="background: #1C1C1E; padding: 30px; text-align: center; border-bottom: 5px solid #FFD60A;">
            <h1 style="color: #FFD60A; margin: 0; font-size: 24px;">Executive Briefing</h1>
            <p style="color: #F9F9F9; font-size: 14px; margin-top: 10px; opacity: 0.8;">${userQuery}</p>
          </header>
          
          <div style="padding: 40px 0;">
            ${analysisHtml}
          </div>

          <footer style="padding: 20px; text-align: center; border-top: 1px solid #EEE; font-size: 12px; color: #999;">
            <p>Generated by My Briefing — AI Career Intelligence · mybriefing.ai</p>
          </footer>
        </div>
      `,
    });

    if (error) {
      console.error("Resend Error:", error);
      return NextResponse.json({ error: "Email failed" }, { status: 500 });
    }

    return NextResponse.json({ success: true, id: data?.id });

  } catch (err: any) {
    console.error("Global Error:", err);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
