import { NextResponse } from "next/server";
import { Resend } from "resend";
import { renderToBuffer } from "@react-pdf/renderer";
import React from "react";
import { BriefingDocument } from "@/components/BriefingDocument";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  console.log(">>> [EMAIL/PDF] Request Received");

  try {
    const body = await req.json();
    const { email, query, fullAnalysis } = body;

    // 1. Validation
    if (!email || !email.includes("@")) {
      return NextResponse.json({ error: "Valid email required" }, { status: 400 });
    }
    if (!fullAnalysis) {
      return NextResponse.json({ error: "No analysis data found" }, { status: 400 });
    }

    const userEmail = email.trim().toLowerCase();
    const userQuery = String(query || "Analysis Briefing");
    
    // 2. Sanitize Data for PDF (Prevents the e.split error)
    // We ensure every piece of data passed to the PDF is a string or valid fallback
    const sanitizedAnalysis = JSON.parse(JSON.stringify(fullAnalysis), (key, value) => {
      return value === null || value === undefined ? "N/A" : value;
    });

    console.log(">>> [EMAIL/PDF] Generating PDF Buffer...");

    // 3. Generate PDF with error isolation
    let pdfBuffer: Buffer;
    try {
      pdfBuffer = await renderToBuffer(
        React.createElement(BriefingDocument, {
          query: userQuery,
          analysis: sanitizedAnalysis,
        })
      );
    } catch (pdfErr: any) {
      console.error(">>> [PDF GEN ERROR]:", pdfErr.message);
      return NextResponse.json({ error: "PDF generation failed", detail: pdfErr.message }, { status: 500 });
    }

    console.log(`>>> [EMAIL/PDF] PDF Generated (${pdfBuffer.length} bytes). Sending email...`);

    // 4. Send via Resend
    // NOTE: Use onboarding@resend.dev until your custom domain is verified in Resend Dashboard
    const { data, error } = await resend.emails.send({
      from: "Briefing Bot <onboarding@resend.dev>", 
      to: [userEmail],
      subject: `Executive Briefing: ${userQuery}`,
      html: `
        <div style="font-family: sans-serif; padding: 20px; color: #1C1C1E;">
          <h2 style="color: #FFD60A; background: #1C1C1E; padding: 10px; display: inline-block;">Intelligence Briefing Confirmed</h2>
          <p>The strategic analysis for <strong>"${userQuery}"</strong> is now ready.</p>
          <p>Please find your full 6-agent briefing attached as a PDF.</p>
          <hr style="border: 1px solid #EEE" />
          <p style="font-size: 12px; color: #666;">Generated by AI Automation Mum // Strategic Systems</p>
        </div>
      `,
      attachments: [
        {
          filename: `Briefing_${userQuery.replace(/[^a-z0-9]/gi, "_").toLowerCase()}.pdf`,
          content: pdfBuffer.toString("base64"), // Convert to Base64 for reliable transfer
        },
      ],
    });

    if (error) {
      console.error(">>> [RESEND ERROR]:", error);
      return NextResponse.json({ error: "Email delivery failed", detail: error }, { status: 500 });
    }

    console.log(">>> [EMAIL/PDF] Success! ID:", data?.id);
    return NextResponse.json({ success: true, id: data?.id });

  } catch (err: any) {
    console.error(">>> [GLOBAL ERROR]:", err.message);
    return NextResponse.json({ error: "Internal Server Error", detail: err.message }, { status: 500 });
  }
}
